//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resourses.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Saratov postcards.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNew.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No postcards in database!.
        /// </summary>
        public static string EmptyDB {
            get {
                return ResourceManager.GetString("EmptyDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First of all, please add publishers, series, postcards and other to database..
        /// </summary>
        public static string EmptyDBHelp {
            get {
                return ResourceManager.GetString("EmptyDBHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find By Name.
        /// </summary>
        public static string FindByName {
            get {
                return ResourceManager.GetString("FindByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer.
        /// </summary>
        public static string Photographer {
            get {
                return ResourceManager.GetString("Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Photographer_FirstName_First_Name {
            get {
                return ResourceManager.GetString("Photographer_FirstName_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be longer than 50 characters..
        /// </summary>
        public static string Photographer_FirstName_First_name_cannot_be_longer_than_50_characters_ {
            get {
                return ResourceManager.GetString("Photographer_FirstName_First_name_cannot_be_longer_than_50_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Photographer_FullName_Full_Name {
            get {
                return ResourceManager.GetString("Photographer_FullName_Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Photographer_LastName_Last_Name {
            get {
                return ResourceManager.GetString("Photographer_LastName_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Photographer_MiddleName_Middle_Name {
            get {
                return ResourceManager.GetString("Photographer_MiddleName_Middle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name cannot be longer than 50 characters..
        /// </summary>
        public static string Photographer_MiddleName_Middle_name_cannot_be_longer_than_50_characters_ {
            get {
                return ResourceManager.GetString("Photographer_MiddleName_Middle_name_cannot_be_longer_than_50_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographers.
        /// </summary>
        public static string Photographers {
            get {
                return ResourceManager.GetString("Photographers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists see your system administrator..
        /// </summary>
        public static string PhotographersController_Create_Unable_to_save_changes__Try_again__and_if_the_problem_persists_see_your_system_administrator_ {
            get {
                return ResourceManager.GetString("PhotographersController_Create_Unable_to_save_changes__Try_again__and_if_the_prob" +
                        "lem_persists_see_your_system_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string PhotographersController_EditPost_Unable_to_save_changes__Try_again__and_if_the_problem_persists__see_your_system_administrator_ {
            get {
                return ResourceManager.GetString("PhotographersController_EditPost_Unable_to_save_changes__Try_again__and_if_the_pr" +
                        "oblem_persists__see_your_system_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcard.
        /// </summary>
        public static string Postcard {
            get {
                return ResourceManager.GetString("Postcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back title font.
        /// </summary>
        public static string Postcard_BackTitleFont_Back_title_font {
            get {
                return ResourceManager.GetString("Postcard_BackTitleFont_Back_title_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back title font color.
        /// </summary>
        public static string Postcard_BackTitleFontColor_Back_title_font_color {
            get {
                return ResourceManager.GetString("Postcard_BackTitleFontColor_Back_title_font_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back title place.
        /// </summary>
        public static string Postcard_BackTitlePlace_Back_title_place {
            get {
                return ResourceManager.GetString("Postcard_BackTitlePlace_Back_title_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back type.
        /// </summary>
        public static string Postcard_BackType_Back_type {
            get {
                return ResourceManager.GetString("Postcard_BackType_Back_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front title font.
        /// </summary>
        public static string Postcard_FrontTitleFont_Front_title_font {
            get {
                return ResourceManager.GetString("Postcard_FrontTitleFont_Front_title_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front title font color.
        /// </summary>
        public static string Postcard_FrontTitleFontColor_Front_title_font_color {
            get {
                return ResourceManager.GetString("Postcard_FrontTitleFontColor_Front_title_font_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image back.
        /// </summary>
        public static string Postcard_ImageLinkBack_Image {
            get {
                return ResourceManager.GetString("Postcard_ImageLinkBack_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image front.
        /// </summary>
        public static string Postcard_ImageLinkFront_Image {
            get {
                return ResourceManager.GetString("Postcard_ImageLinkFront_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number in series.
        /// </summary>
        public static string Postcard_NumberInSeries_Number_in_series {
            get {
                return ResourceManager.GetString("Postcard_NumberInSeries_Number_in_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer.
        /// </summary>
        public static string Postcard_PhotographerId_Photographer {
            get {
                return ResourceManager.GetString("Postcard_PhotographerId_Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post date.
        /// </summary>
        public static string Postcard_PostDate_Post_date {
            get {
                return ResourceManager.GetString("Postcard_PostDate_Post_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Postcard_SeriesId_Series {
            get {
                return ResourceManager.GetString("Postcard_SeriesId_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Postcard_Title_Title {
            get {
                return ResourceManager.GetString("Postcard_Title_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Postcard_Year_Year {
            get {
                return ResourceManager.GetString("Postcard_Year_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcards.
        /// </summary>
        public static string Postcards {
            get {
                return ResourceManager.GetString("Postcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string PostcardsController_Create_Unable_to_save_changes__Try_again__and_if_the_problem_persists__see_your_system_administrator_ {
            get {
                return ResourceManager.GetString("PostcardsController_Create_Unable_to_save_changes__Try_again__and_if_the_problem_" +
                        "persists__see_your_system_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcards Manager.
        /// </summary>
        public static string PostcardsManager {
            get {
                return ResourceManager.GetString("PostcardsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Publisher_Name_Name {
            get {
                return ResourceManager.GetString("Publisher_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete. Try again, and if the problem persists contact your system administrator..
        /// </summary>
        public static string PublisherController_Delete_Unable_to_delete__Try_again__and_if_the_problem_persists_contact_your_system_administrator_ {
            get {
                return ResourceManager.GetString("PublisherController_Delete_Unable_to_delete__Try_again__and_if_the_problem_persis" +
                        "ts_contact_your_system_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string PublisherController_EditPost_Unable_to_save_changes__Try_again__and_if_the_problem_persists__see_your_system_administrator_ {
            get {
                return ResourceManager.GetString("PublisherController_EditPost_Unable_to_save_changes__Try_again__and_if_the_proble" +
                        "m_persists__see_your_system_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Photographer.
        /// </summary>
        public static string SelectPhotographer {
            get {
                return ResourceManager.GetString("SelectPhotographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Publisher:.
        /// </summary>
        public static string SelectPublisher {
            get {
                return ResourceManager.GetString("SelectPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Series:.
        /// </summary>
        public static string SelectSeries {
            get {
                return ResourceManager.GetString("SelectSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Series_PublisherId_Publisher {
            get {
                return ResourceManager.GetString("Series_PublisherId_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Series_Title_Title {
            get {
                return ResourceManager.GetString("Series_Title_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Series_Year_Year {
            get {
                return ResourceManager.GetString("Series_Year_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string SeriesController_Create_Unable_to_save_changes__Try_again__and_if_the_problem_persists__see_your_system_administrator_ {
            get {
                return ResourceManager.GetString("SeriesController_Create_Unable_to_save_changes__Try_again__and_if_the_problem_per" +
                        "sists__see_your_system_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
